In [1]:
import pandas as pd
import numpy as np

In [2]:
Companies_Df=pd.read_csv("companies.txt",sep="\t",encoding="ANSI")
Companies_Df

,permalink,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/Organization/-Fame,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/Organization/-Qounter,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/Organization/-The-One-Of-Them-Inc-,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
3,/Organization/0-6-Com,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007
4,/Organization/004-Technologies,004 Technologies,http://004gmbh.de/en/004-interact,Software,operating,USA,IL,"Springfield, Illinois",Champaign,01-01-2010
5,/Organization/01Games-Technology,01Games Technology,http://www.01games.hk/,Games,operating,HKG,NaN,Hong Kong,Hong Kong,NaN
6,/Organization/0Ndine-Biomedical-Inc,Ondine Biomedical Inc.,http://ondinebio.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-01-1997
7,/Organization/0Xdata,H2O.ai,http://h2o.ai/,Analytics,operating,USA,CA,SF Bay Area,Mountain View,01-01-2011
8,/Organization/1,One Inc.,http://whatis1.com,Mobile,operating,USA,CA,SF Bay Area,San Francisco,01-08-2011
9,/Organization/1-2-3-Listo,"1,2,3 Listo",http://www.123listo.com,E-Commerce,operating,CHL,12,Santiago,Las Condes,01-01-2012
10,/Organization/1-4-All,1-4 All,NaN,Entertainment|Games|Software,operating,USA,NC,NC - Other,Connellys Springs,NaN
11,/Organization/1-618-Technology,1.618 Technology,http://www.Homeandcondogallery.com,Networking|Real Estate|Web Hosting,operating,USA,FL,Orlando,Orlando,07-12-2013
12,/Organization/1-800-Dentist,1-800-DENTIST,http://www.1800dentist.com,Health and Wellness,operating,USA,CA,Los Angeles,Los Angeles,01-01-1986
13,/Organization/1-800-Doctors,1-800-DOCTORS,http://1800doctors.com,Health and Wellness,operating,USA,NJ,Newark,Iselin,01-01-1984
14,/Organization/1-800-Publicrelations-Inc-,"1-800-PublicRelations, Inc.",http://www.1800publicrelations.com,Internet Marketing|Media|Public Relations,operating,USA,NY,New York City,New York,24-10-2013
15,/Organization/1-Mainstream,1 Mainstream,http://www.1mainstream.com,Apps|Cable|Distribution|Software,acquired,USA,CA,SF Bay Area,Cupertino,01-03-2012
16,/Organization/1-Of-99,1 of 99,NaN,Entertainment|Games,operating,USA,CA,SF Bay Area,Mountain View,01-12-2014
17,/Organization/10-20-Media,10-20 Media,http://www.10-20media.com,E-Commerce,operating,USA,MD,Baltimore,Woodbine,01-01-2001
18,/Organization/10-Minutes-With,10 Minutes With,http://10minuteswith.com,Education,operating,GBR,H9,London,London,01-01-2013
19,/Organization/1000-Corks,1000 Corks,http://1000corks.com,Search,operating,USA,OR,"Portland, Oregon",Lake Oswego,01-01-2008
20,/Organization/1000-Markets,1000 Markets,http://www.1000markets.com,Art|E-Commerce|Marketplaces,acquired,USA,WA,Seattle,Seattle,01-01-2009
21,/Organization/1000Chi,Beijing 1000CHI Software Technology,http://www.1000chi.com/,Mobile,operating,NaN,NaN,NaN,NaN,01-01-2008
22,/Organization/1000Lookz,1000Lookz,http://1000lookz.com,Beauty,operating,IND,25,Chennai,Chennai,01-01-2008
23,/Organization/1000Memories,1000memories,http://1000memories.com,Curated Web,acquired,USA,CA,SF Bay Area,San Francisco,01-07-2010
24,/Organization/1000Museums-Com,1000museums.com,http://www.1000museums.com,Curated Web,operating,USA,MA,MA - Other,Lenox,01-01-2008
25,/Organization/1001-Menus,ZenChef,http://zenchef.com/en/,Local Businesses|Restaurants,operating,FRA,A8,Paris,Paris,20-11-2010
26,/Organization/1001Pharmacies-Com,1001pharmacies.com,http://www.1001pharmacies.com/,Cosmetics|Marketplaces,operating,FRA,A9,Montpellier,Montpellier,01-01-2012
27,/Organization/1006-Tv,1006.tv,http://www.1006.tv/,Games|Media,operating,CHN,22,Beijing,Beijing,01-01-2009
28,/Organization/100Du-Tv,100du.tv,http://www.100du.com,Hospitality,operating,CHN,23,Shanghai,Shanghai,NaN
29,/Organization/100E-Com,100e.com,http://www.100e.com,Education,operating,CHN,22,Beijing,Beijing,NaN
...,...,...,...,...,...,...,...,...,...,...
66338,/Organization/Zykis,Zykis,http://zykis.com,Automotive|Data Security|Education|Kids|Portal...,closed,USA,CA,Anaheim,Irvine,27-10-2006
66339,/Organization/Zylie-The-Bear,Zylie the Bear,http://zyliethebear.com,E-Commerce,operating,USA,CT,Hartford,Greenwich,01-01-2009
66340,/Organization/Zylun-Staffing,Zylun Staffing,http://www.zylun.com,Software,operating,USA,UT,Salt Lake City,Lehi,01-01-2010
66341,/Organization/Zyme-Solutions,Zyme Solutions,http://www.zymesolutions.com,Hardware|Hardware + Software,operating,USA,CA,SF Bay Area,Redwood Shores,01-01-2004
66342,/Organization/Zymergen,Zymergen,http://www.zymergen.com,Biotechnology,operating,USA,CA,SF Bay Area,Emeryville,01-01-2013
66343,/Organization/Zymetis,Zymetis,http://www.zymetis.com,Biotechnology,closed,USA,MD,"Washington, D.C.",College Park,01-01-2006
66344,/Organization/Zymeworks,Zymeworks,http://zymeworks.com,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,01-04-2004
66345,/Organization/Zymochem,Zymochem,http://www.zymochem.com,Specialty Chemicals,operating,USA,CA,SF Bay Area,San Francisco,01-05-2013
66346,/Organization/Zympi,Zympi,http://www.zympi.com,Mobile|Networking|Web Hosting,operating,USA,CA,Ontario - Inland Empire,Redlands,03-09-2010
66347,/Organization/Zymr-Inc-,"Zymr, Inc.",http://www.zymr.com,Android|Apps|Cloud Computing|Cloud Infrastruct...,operating,USA,CA,SF Bay Area,Santa Clara,NaN
66348,/Organization/Zyncd,Zyncd,http://www.zyncd.com,Crowdsourcing|Knowledge Management,operating,GBR,H9,London,London,01-01-2014
66349,/Organization/Zyncro,Zyncro,http://www.zyncro.com,Cloud Computing|Enterprise 2.0|Enterprise Soft...,acquired,ESP,56,Barcelona,Barcelona,01-09-2009
66350,/Organization/Zynerba-Pharmaceuticals,Zynerba Pharmaceuticals,http://zynerba.com,Pharmaceuticals,ipo,USA,PA,Philadelphia,Radnor,01-01-2014
66351,/Organization/Zynergy-Projects-Services,Zynergy Projects & Services,http://www.zynergygroup.net/,Clean Technology,operating,IND,25,Chennai,Chennai,NaN
66352,/Organization/Zynga,Zynga,http://www.zynga.com,Facebook Applications|Games|Networking|Technology,ipo,USA,CA,SF Bay Area,San Francisco,01-07-2007
66353,/Organization/Zyngenia,Zyngenia,http://www.zyngenia.com,Biotechnology,operating,USA,MD,"Washington, D.C.",Gaithersburg,01-01-2008
66354,/Organization/Zynstra,Zynstra,http://www.zynstra.com,Software,operating,GBR,A4,Bath,Bath,30-11-2011
66355,/Organization/Zyomyx-Inc,ZYOMYX,http://www.zyomyx.com,Biotechnology,operating,USA,MO,MO - Other,Fremont,01-01-1998
66356,/Organization/Zype,Zype,http://www.zype.com,Cloud Computing|Mobile Advertising|Video|Video...,operating,USA,NY,New York City,New York,01-01-2013
66357,/Organization/Zypsee,Whisk (formerly Zypsee),http://whisk.me,Public Transportation,operating,USA,NY,New York City,New York,01-01-2011
66358,/Organization/Zyraz-Technology,Zyraz Technology,http://www.zyraz.com,Biotechnology,closed,MYS,14,MYS - Other,Damansara New Village,01-01-1994
66359,/Organization/Zyrra,Zyrra,http://www.zyrra.com,E-Commerce,operating,USA,MA,Boston,Cambridge,NaN
66360,/Organization/Zystor,Zystor,http://www.zystor.com,Biotechnology,acquired,USA,WI,Milwaukee,Milwaukee,NaN
66361,/Organization/Zytoprotec,Zytoprotec,http://www.zytoprotec.com,Biotechnology,operating,AUT,3,Vienna,Gerasdorf Bei Wien,01-01-2007
66362,/Organization/Zzish,Zzish,http://www.zzish.com,Analytics|Android|Developer APIs|Education|Gam...,operating,GBR,H9,London,London,28-01-2014
66363,/Organization/Zznode-Science-And-Technology-Co...,ZZNode Science and Technology,http://www.zznode.com,Enterprise Software,operating,CHN,22,Beijing,Beijing,NaN
66364,/Organization/Zzzzapp-Com,Zzzzapp Wireless ltd.,http://www.zzzzapp.com,Advertising|Mobile|Web Development|Wireless,operating,HRV,15,Split,Split,13-05-2012
66365,/Organization/ÃEron,ÃERON,http://www.aeron.hu/,NaN,operating,NaN,NaN,NaN,NaN,01-01-2011
66366,/Organization/Ã”Asys-2,Ã”asys,http://www.oasys.io/,Consumer Electronics|Internet of Things|Teleco...,operating,USA,CA,SF Bay Area,San Francisco,01-01-2014
66367,/Organization/Ä°Novatiff-Reklam-Ve-Tanä±Tä±M-H...,Ä°novatiff Reklam ve TanÄ±tÄ±m Hizmetleri Tic,http://inovatiff.com,Consumer Goods|E-Commerce|Internet,operating,NaN,NaN,NaN,NaN,NaN

In [10]:
Rounds2=pd.read_csv("rounds2.csv",encoding="ANSI")
Rounds2.head()

,company_permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/ORGANIZATION/-QOUNTER,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/ORGANIZATION/-THE-ONE-OF-THEM-INC-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [11]:
Rounds2.company_permalink=Rounds2.company_permalink.str.lower()
Rounds2.company_permalink

0                                       /organization/-fame
1                                    /organization/-qounter
2                                    /organization/-qounter
3                       /organization/-the-one-of-them-inc-
4                                     /organization/0-6-com
5                            /organization/004-technologies
6                          /organization/01games-technology
7                       /organization/0ndine-biomedical-inc
8                       /organization/0ndine-biomedical-inc
9                                      /organization/0xdata
10                                     /organization/0xdata
11                                     /organization/0xdata
12                                     /organization/0xdata
13                                          /organization/1
14                                          /organization/1
15                                          /organization/1
16                                /organization/1-2-3-listo
17                                    /organization/1-4-all
18                           /organization/1-618-technology
19                              /organization/1-800-dentist
20                              /organization/1-800-doctors
21                 /organization/1-800-publicrelations-inc-
22                               /organization/1-mainstream
23                                    /organization/1-of-99
24                                /organization/10-20-media
25                                /organization/10-20-media
26                                /organization/10-20-media
27                                /organization/10-20-media
28                            /organization/10-minutes-with
29                            /organization/10-minutes-with
                                ...
114919                                /organization/zynstra
114920                             /organization/zyomyx-inc
114921                             /organization/zyomyx-inc
114922                             /organization/zyomyx-inc
114923                             /organization/zyomyx-inc
114924                                   /organization/zype
114925                                   /organization/zype
114926                                 /organization/zypsee
114927                                 /organization/zypsee
114928                       /organization/zyraz-technology
114929                       /organization/zyraz-technology
114930                       /organization/zyraz-technology
114931                       /organization/zyraz-technology
114932                                  /organization/zyrra
114933                                  /organization/zyrra
114934                                  /organization/zyrra
114935                                  /organization/zyrra
114936                                 /organization/zystor
114937                             /organization/zytoprotec
114938                                  /organization/zzish
114939                                  /organization/zzish
114940                                  /organization/zzish
114941    /organization/zznode-science-and-technology-co...
114942                            /organization/zzzzapp-com
114943                            /organization/zzzzapp-com
114944                            /organization/zzzzapp-com
114945                            /organization/zzzzapp-com
114946                                 /organization/ãeron
114947                               /organization/ã”asys-2
114948    /organization/ä°novatiff-reklam-ve-tanä±tä±m-h...
Name: company_permalink, Length: 114949, dtype: object

In [12]:
Companies_Df.permalink=Companies_Df.permalink.str.lower()
Companies_Df.permalink

0                                      /organization/-fame
1                                   /organization/-qounter
2                      /organization/-the-one-of-them-inc-
3                                    /organization/0-6-com
4                           /organization/004-technologies
5                         /organization/01games-technology
6                      /organization/0ndine-biomedical-inc
7                                     /organization/0xdata
8                                          /organization/1
9                                /organization/1-2-3-listo
10                                   /organization/1-4-all
11                          /organization/1-618-technology
12                             /organization/1-800-dentist
13                             /organization/1-800-doctors
14                /organization/1-800-publicrelations-inc-
15                              /organization/1-mainstream
16                                   /organization/1-of-99
17                               /organization/10-20-media
18                           /organization/10-minutes-with
19                                /organization/1000-corks
20                              /organization/1000-markets
21                                   /organization/1000chi
22                                 /organization/1000lookz
23                              /organization/1000memories
24                           /organization/1000museums-com
25                                /organization/1001-menus
26                        /organization/1001pharmacies-com
27                                   /organization/1006-tv
28                                  /organization/100du-tv
29                                  /organization/100e-com
                               ...
66338                                  /organization/zykis
66339                         /organization/zylie-the-bear
66340                         /organization/zylun-staffing
66341                         /organization/zyme-solutions
66342                               /organization/zymergen
66343                                /organization/zymetis
66344                              /organization/zymeworks
66345                               /organization/zymochem
66346                                  /organization/zympi
66347                              /organization/zymr-inc-
66348                                  /organization/zyncd
66349                                 /organization/zyncro
66350                /organization/zynerba-pharmaceuticals
66351              /organization/zynergy-projects-services
66352                                  /organization/zynga
66353                               /organization/zyngenia
66354                                /organization/zynstra
66355                             /organization/zyomyx-inc
66356                                   /organization/zype
66357                                 /organization/zypsee
66358                       /organization/zyraz-technology
66359                                  /organization/zyrra
66360                                 /organization/zystor
66361                             /organization/zytoprotec
66362                                  /organization/zzish
66363    /organization/zznode-science-and-technology-co...
66364                            /organization/zzzzapp-com
66365                                 /organization/ãeron
66366                               /organization/ã”asys-2
66367    /organization/ä°novatiff-reklam-ve-tanä±tä±m-h...
Name: permalink, Length: 66368, dtype: object

In [13]:
Companies_Df.permalink.nunique()

66368

In [14]:
Rounds2.company_permalink.nunique()

66368

In [15]:
Rounds2=Rounds2.rename({"company_permalink":"permalink"}, axis='columns')
Rounds2.head()

,permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0

In [16]:
master_df=pd.merge(Rounds2,Companies_Df,how='inner',on='permalink')

In [17]:
master_df.head()

,permalink,funding_round_permalink,funding_round_type,funding_round_code,funded_at,raised_amount_usd,name,homepage_url,category_list,status,country_code,state_code,region,city,founded_at
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,B,05-01-2015,10000000.0,#fame,http://livfame.com,Media,operating,IND,16,Mumbai,Mumbai,NaN
1,/organization/-qounter,/funding-round/22dacff496eb7acb2b901dec1dfe5633,venture,A,14-10-2014,NaN,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
2,/organization/-qounter,/funding-round/b44fbb94153f6cdef13083530bb48030,seed,NaN,01-03-2014,700000.0,:Qounter,http://www.qounter.com,Application Platforms|Real Time|Social Network...,operating,USA,DE,DE - Other,Delaware City,04-09-2014
3,/organization/-the-one-of-them-inc-,/funding-round/650b8f704416801069bb178a1418776b,venture,B,30-01-2014,3406878.0,"(THE) ONE of THEM,Inc.",http://oneofthem.jp,Apps|Games|Mobile,operating,NaN,NaN,NaN,NaN,NaN
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,A,19-03-2008,2000000.0,0-6.com,http://www.0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,01-01-2007

In [18]:
master_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 114949 entries, 0 to 114948
Data columns (total 15 columns):
permalink                  114949 non-null object
funding_round_permalink    114949 non-null object
funding_round_type         114949 non-null object
funding_round_code         31140 non-null object
funded_at                  114949 non-null object
raised_amount_usd          94959 non-null float64
name                       114948 non-null object
homepage_url               108815 non-null object
category_list              111539 non-null object
status                     114949 non-null object
country_code               106271 non-null object
state_code                 104003 non-null object
region                     104782 non-null object
city                       104785 non-null object
founded_at                 94428 non-null object
dtypes: float64(1), object(14)
memory usage: 14.0+ MB

In [19]:
round(100*(master_df.isnull().sum()/len(master_df.index)), 2)

permalink                   0.00
funding_round_permalink     0.00
funding_round_type          0.00
funding_round_code         72.91
funded_at                   0.00
raised_amount_usd          17.39
name                        0.00
homepage_url                5.34
category_list               2.97
status                      0.00
country_code                7.55
state_code                  9.52
region                      8.84
city                        8.84
founded_at                 17.85
dtype: float64

In [20]:
#Remove the columns founded_at, funding_round_code, homepage_url  

master_df= master_df.drop('funding_round_code',axis=1)
master_df= master_df.drop('founded_at',axis=1)
master_df= master_df.drop('homepage_url',axis=1)

In [21]:
round(100*(master_df.isnull().sum()/len(master_df.index)), 2)

permalink                   0.00
funding_round_permalink     0.00
funding_round_type          0.00
funded_at                   0.00
raised_amount_usd          17.39
name                        0.00
category_list               2.97
status                      0.00
country_code                7.55
state_code                  9.52
region                      8.84
city                        8.84
dtype: float64

In [22]:
#remove the rows where raised_amount_usd has null values.
master_df = master_df[~np.isnan(master_df['raised_amount_usd'])]

In [23]:
round(100*(master_df.isnull().sum()/len(master_df.index)), 2)

permalink                  0.00
funding_round_permalink    0.00
funding_round_type         0.00
funded_at                  0.00
raised_amount_usd          0.00
name                       0.00
category_list              1.10
status                     0.00
country_code               6.16
state_code                 8.01
region                     7.42
city                       7.42
dtype: float64

In [24]:
#use dropna function to drop remaining missing values inside each row.
master_df.dropna(axis=0,how="any",inplace=True)

In [25]:
round(100*(master_df.isnull().sum()/len(master_df.index)), 2)

permalink                  0.0
funding_round_permalink    0.0
funding_round_type         0.0
funded_at                  0.0
raised_amount_usd          0.0
name                       0.0
category_list              0.0
status                     0.0
country_code               0.0
state_code                 0.0
region                     0.0
city                       0.0
dtype: float64

In [26]:
master_df.shape

(86443, 12)

All The Missing Values are removed.

In [27]:
#To check the funding round type to invest
master_df.groupby("funding_round_type").raised_amount_usd.mean().sort_values(ascending=False)

funding_round_type
post_ipo_debt            1.704481e+08
secondary_market         8.443853e+07
private_equity           7.082810e+07
post_ipo_equity          6.441423e+07
undisclosed              1.674154e+07
debt_financing           1.655967e+07
venture                  1.174273e+07
grant                    4.607961e+06
product_crowdfunding     1.357667e+06
convertible_note         1.353095e+06
angel                    9.776435e+05
seed                     7.424383e+05
equity_crowdfunding      5.054366e+05
non_equity_assistance    4.883933e+05
Name: raised_amount_usd, dtype: float64

In [28]:
#Average or mean of seed fund
master_df[master_df.funding_round_type=="seed"].raised_amount_usd.mean()

742438.3398949486

In [29]:
#Average or mean of angel fund
master_df[master_df.funding_round_type=="angel"].raised_amount_usd.mean()

977643.5281871345

In [30]:
#Average or mean of venture fund
master_df[master_df.funding_round_type=="venture"].raised_amount_usd.mean()

11742729.663460309

In [31]:
#Average or mean of venture fund
master_df[master_df.funding_round_type=="private_equity"].raised_amount_usd.mean()

70828095.70561543

In [32]:
#Above all Only venture falls in the category to invest between 5-15 million usd.
#So we have to perform analysis further only for venture type of fundings.

master_df=master_df[master_df.funding_round_type=="venture"]
master_df.shape

(46886, 12)

In [33]:
#To choose the top 3 english speaking countries to invest in where maximum people have invested in
master_df.groupby("country_code").raised_amount_usd.sum().sort_values(ascending=False)

country_code
USA    4.194432e+11
CHN    3.695087e+10
GBR    1.923553e+10
IND    1.416781e+10
CAN    9.435487e+09
FRA    6.825021e+09
ISR    6.551761e+09
DEU    6.180782e+09
JPN    3.018150e+09
SWE    3.017689e+09
CHE    2.684062e+09
NLD    2.654940e+09
ESP    1.819382e+09
BRA    1.747918e+09
IRL    1.669286e+09
RUS    1.542576e+09
AUS    1.312004e+09
DNK    1.174336e+09
FIN    1.032591e+09
BEL    1.019927e+09
MYS    8.790588e+08
KOR    8.743854e+08
NOR    8.682217e+08
AUT    5.792207e+08
TWN    5.627740e+08
TUR    5.590975e+08
ITA    4.855220e+08
NZL    4.385176e+08
ARE    3.426175e+08
LUX    3.219207e+08
           ...
ARM    2.651750e+07
LVA    2.367934e+07
ROM    1.840665e+07
UKR    1.779246e+07
KNA    1.500000e+07
KWT    1.400000e+07
LIE    1.309172e+07
SVN    1.201751e+07
BGR    1.130000e+07
KAZ    1.100000e+07
GRC    1.074378e+07
BAH    8.900000e+06
TTO    8.500000e+06
BGD    7.002000e+06
LBN    6.305000e+06
SVK    4.591062e+06
TUN    3.920000e+06
SEN    2.860000e+06
HRV    2.633669e+06
UGA    2.500000e+06
PER    2.469270e+06
PAN    2.100000e+06
LAO    2.100000e+06
MAR    1.600000e+06
MUS    1.500000e+06
ECU    9.658500e+05
SAU    5.000000e+05
GTM    3.000000e+05
MMR    2.000000e+05
CMR    4.561000e+03
Name: raised_amount_usd, Length: 84, dtype: float64

In [34]:
#Sector wise analysis
#Spliting into one primary sector
master_df['primary_sector']=master_df.category_list.map(lambda x: str(x).split('|')[0])

In [35]:
master_df.head()

,permalink,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,name,category_list,status,country_code,state_code,region,city,primary_sector
0,/organization/-fame,/funding-round/9a01d05418af9f794eebff7ace91f638,venture,05-01-2015,10000000.0,#fame,Media,operating,IND,16,Mumbai,Mumbai,Media
4,/organization/0-6-com,/funding-round/5727accaeaa57461bd22a9bdd945382d,venture,19-03-2008,2000000.0,0-6.com,Curated Web,operating,CHN,22,Beijing,Beijing,Curated Web
8,/organization/0ndine-biomedical-inc,/funding-round/954b9499724b946ad8c396a57a5f3b72,venture,21-12-2009,719491.0,Ondine Biomedical Inc.,Biotechnology,operating,CAN,BC,Vancouver,Vancouver,Biotechnology
10,/organization/0xdata,/funding-round/3bb2ee4a2d89251a10aaa735b1180e44,venture,09-11-2015,20000000.0,H2O.ai,Analytics,operating,USA,CA,SF Bay Area,Mountain View,Analytics
11,/organization/0xdata,/funding-round/ae2a174c06517c2394aed45006322a7e,venture,03-01-2013,1700000.0,H2O.ai,Analytics,operating,USA,CA,SF Bay Area,Mountain View,Analytics

In [36]:
#Importing mapping csv files
mapping=pd.read_csv("mapping.csv",encoding="ANSI")
mapping['category_list'] = mapping['category_list'].str.replace('0','na')
mapping

,category_list,Automotive & Sports,Blanks,Cleantech / Semiconductors,Entertainment,Health,Manufacturing,"News, Search and Messaging",Others,"Social, Finance, Analytics, Advertising"
0,NaN,0,1,0,0,0,0,0,0,0
1,3D,0,0,0,0,0,1,0,0,0
2,3D Printing,0,0,0,0,0,1,0,0,0
3,3D Technology,0,0,0,0,0,1,0,0,0
4,Accounting,0,0,0,0,0,0,0,0,1
5,Active Lifestyle,0,0,0,0,1,0,0,0,0
6,Ad Targeting,0,0,0,0,0,0,0,0,1
7,Advanced Materials,0,0,0,0,0,1,0,0,0
8,Adventure Travel,1,0,0,0,0,0,0,0,0
9,Advertising,0,0,0,0,0,0,0,0,1
10,Advertising Exchanges,0,0,0,0,0,0,0,0,1
11,Advertising Networks,0,0,0,0,0,0,0,0,1
12,Advertising Platforms,0,0,0,0,0,0,0,0,1
13,Advice,0,0,0,0,0,0,0,1,0
14,Aerospace,1,0,0,0,0,0,0,0,0
15,Agriculture,0,0,0,0,0,1,0,0,0
16,Air Pollution Control,0,0,1,0,0,0,0,0,0
17,Algorithms,0,0,0,0,0,0,0,1,0
18,All Markets,0,0,0,0,0,0,0,1,0
19,All Students,0,0,0,0,0,0,0,1,0
20,Alternative Medicine,0,0,0,0,1,0,0,0,0
21,Alumni,0,0,0,0,0,0,0,1,0
22,Analytics,0,0,0,0,0,0,0,0,1
23,Android,0,0,0,0,0,0,0,0,1
24,Angels,0,0,0,0,0,0,0,1,0
25,Animal Feed,0,0,0,0,1,0,0,0,0
26,Anything Capital Intensive,0,0,0,0,0,0,0,0,1
27,App Discovery,0,0,0,0,0,0,1,0,0
28,App Marketing,0,0,0,0,0,0,1,0,0
29,App Stores,0,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...
658,Usability,0,0,0,0,0,0,0,1,0
659,User Experience Design,0,0,0,0,0,0,0,1,0
660,User Interface,0,0,0,0,0,0,0,1,0
661,Utilities,0,0,0,0,0,0,0,1,0
662,Vending and Concessions,0,0,0,0,0,0,0,1,0
663,Venture Capital,0,0,0,0,0,0,0,0,1
664,Veterinary,0,0,0,0,1,0,0,0,0
665,Video,0,0,0,1,0,0,0,0,0
666,Video Conferencing,0,0,0,1,0,0,0,0,0
667,Video Games,0,0,0,1,0,0,0,0,0
668,Video on Demand,0,0,0,1,0,0,0,0,0
669,Video Streaming,0,0,0,1,0,0,0,0,0
670,Virtual Workforces,0,0,0,1,0,0,0,0,0
671,VoIP,0,0,0,1,0,0,0,0,0
672,Waste Management,0,0,1,0,0,0,0,0,0
673,Watch,0,0,0,0,0,0,0,1,0
674,Water,0,0,1,0,0,0,0,0,0
675,Water Purification,0,0,1,0,0,0,0,0,0
676,Wearables,0,0,1,0,0,0,0,0,0
677,Web Browsers,0,0,0,0,0,0,1,0,0
678,Web Design,0,0,0,0,0,0,1,0,0
679,Web Development,0,0,0,0,0,0,0,1,0
680,Web Hosting,0,0,0,0,0,0,0,1,0
681,Web Tools,0,0,0,0,0,0,0,1,0
682,Weddings,0,0,0,1,0,0,0,0,0
683,Wholesale,0,0,0,0,0,0,0,1,0
684,Wine And Spirits,0,0,0,1,0,0,0,0,0
685,Wireless,0,0,0,1,0,0,0,0,0
686,Women,0,0,0,0,0,0,0,1,0
687,Young Adults,0,0,0,0,0,0,0,1,0

In [37]:
#Offset which consists of only category_list and the main_sector
offset_mapping=pd.DataFrame()

In [38]:
#changing the index to apply argmax
mapping.set_index("category_list",inplace=True)

In [39]:
#Creating a new column Main_Sector which has the main_sector of the category
offset_mapping['Main_Sector']=mapping.idxmax(axis=1)
offset_mapping

                                                        Main_Sector
category_list
NaN                                                          Blanks
3D                                                    Manufacturing
3D Printing                                           Manufacturing
3D Technology                                         Manufacturing
Accounting                  Social, Finance, Analytics, Advertising
Active Lifestyle                                             Health
Ad Targeting                Social, Finance, Analytics, Advertising
Advanced Materials                                    Manufacturing
Adventure Travel                                Automotive & Sports
Advertising                 Social, Finance, Analytics, Advertising
Advertising Exchanges       Social, Finance, Analytics, Advertising
Advertising Networks        Social, Finance, Analytics, Advertising
Advertising Platforms       Social, Finance, Analytics, Advertising
Advice                                                       Others
Aerospace                                       Automotive & Sports
Agriculture                                           Manufacturing
Air Pollution Control                    Cleantech / Semiconductors
Algorithms                                                   Others
All Markets                                                  Others
All Students                                                 Others
Alternative Medicine                                         Health
Alumni                                                       Others
Analytics                   Social, Finance, Analytics, Advertising
Android                     Social, Finance, Analytics, Advertising
Angels                                                       Others
Animal Feed                                                  Health
Anything Capital Intensive  Social, Finance, Analytics, Advertising
App Discovery                            News, Search and Messaging
App Marketing                            News, Search and Messaging
App Stores                               News, Search and Messaging
...                                                             ...
Usability                                                    Others
User Experience Design                                       Others
User Interface                                               Others
Utilities                                                    Others
Vending and Concessions                                      Others
Venture Capital             Social, Finance, Analytics, Advertising
Veterinary                                                   Health
Video                                                 Entertainment
Video Conferencing                                    Entertainment
Video Games                                           Entertainment
Video on Demand                                       Entertainment
Video Streaming                                       Entertainment
Virtual Workforces                                    Entertainment
VoIP                                                  Entertainment
Waste Management                         Cleantech / Semiconductors
Watch                                                        Others
Water                                    Cleantech / Semiconductors
Water Purification                       Cleantech / Semiconductors
Wearables                                Cleantech / Semiconductors
Web Browsers                             News, Search and Messaging
Web Design                               News, Search and Messaging
Web Development                                              Others
Web Hosting                                                  Others
Web Tools                                                    Others
Weddings                                              Entertainment
Wholesale                                                    Others
Wine And Spirits                                      Entertainment
Wireless                                              Entertainment
Women                                                        Others
Young Adults                                                 Others

[688 rows x 1 columns]

In [40]:
#Reset the index back to mapping
offset_mapping.reset_index(level=0, inplace=True)
offset_mapping

                  category_list                              Main_Sector
0                           NaN                                   Blanks
1                            3D                            Manufacturing
2                   3D Printing                            Manufacturing
3                 3D Technology                            Manufacturing
4                    Accounting  Social, Finance, Analytics, Advertising
5              Active Lifestyle                                   Health
6                  Ad Targeting  Social, Finance, Analytics, Advertising
7            Advanced Materials                            Manufacturing
8              Adventure Travel                      Automotive & Sports
9                   Advertising  Social, Finance, Analytics, Advertising
10        Advertising Exchanges  Social, Finance, Analytics, Advertising
11         Advertising Networks  Social, Finance, Analytics, Advertising
12        Advertising Platforms  Social, Finance, Analytics, Advertising
13                       Advice                                   Others
14                    Aerospace                      Automotive & Sports
15                  Agriculture                            Manufacturing
16        Air Pollution Control               Cleantech / Semiconductors
17                   Algorithms                                   Others
18                  All Markets                                   Others
19                 All Students                                   Others
20         Alternative Medicine                                   Health
21                       Alumni                                   Others
22                    Analytics  Social, Finance, Analytics, Advertising
23                      Android  Social, Finance, Analytics, Advertising
24                       Angels                                   Others
25                  Animal Feed                                   Health
26   Anything Capital Intensive  Social, Finance, Analytics, Advertising
27                App Discovery               News, Search and Messaging
28                App Marketing               News, Search and Messaging
29                   App Stores               News, Search and Messaging
..                          ...                                      ...
658                   Usability                                   Others
659      User Experience Design                                   Others
660              User Interface                                   Others
661                   Utilities                                   Others
662     Vending and Concessions                                   Others
663             Venture Capital  Social, Finance, Analytics, Advertising
664                  Veterinary                                   Health
665                       Video                            Entertainment
666          Video Conferencing                            Entertainment
667                 Video Games                            Entertainment
668             Video on Demand                            Entertainment
669             Video Streaming                            Entertainment
670          Virtual Workforces                            Entertainment
671                        VoIP                            Entertainment
672            Waste Management               Cleantech / Semiconductors
673                       Watch                                   Others
674                       Water               Cleantech / Semiconductors
675          Water Purification               Cleantech / Semiconductors
676                   Wearables               Cleantech / Semiconductors
677                Web Browsers               News, Search and Messaging
678                  Web Design               News, Search and Messaging
679             Web Development                                   Others
680                 Web Hosting                                   Others
681                   Web Tools                                   Others
682                    Weddings                            Entertainment
683                   Wholesale                                   Others
684            Wine And Spirits                            Entertainment
685                    Wireless                            Entertainment
686                       Women                                   Others
687                Young Adults                                   Others

[688 rows x 2 columns]

In [41]:
#Renaming the column to primary_sector to merge the dataframes
offset_mapping=offset_mapping.rename({"category_list":"primary_sector"}, axis='columns')
offset_mapping

                 primary_sector                              Main_Sector
0                           NaN                                   Blanks
1                            3D                            Manufacturing
2                   3D Printing                            Manufacturing
3                 3D Technology                            Manufacturing
4                    Accounting  Social, Finance, Analytics, Advertising
5              Active Lifestyle                                   Health
6                  Ad Targeting  Social, Finance, Analytics, Advertising
7            Advanced Materials                            Manufacturing
8              Adventure Travel                      Automotive & Sports
9                   Advertising  Social, Finance, Analytics, Advertising
10        Advertising Exchanges  Social, Finance, Analytics, Advertising
11         Advertising Networks  Social, Finance, Analytics, Advertising
12        Advertising Platforms  Social, Finance, Analytics, Advertising
13                       Advice                                   Others
14                    Aerospace                      Automotive & Sports
15                  Agriculture                            Manufacturing
16        Air Pollution Control               Cleantech / Semiconductors
17                   Algorithms                                   Others
18                  All Markets                                   Others
19                 All Students                                   Others
20         Alternative Medicine                                   Health
21                       Alumni                                   Others
22                    Analytics  Social, Finance, Analytics, Advertising
23                      Android  Social, Finance, Analytics, Advertising
24                       Angels                                   Others
25                  Animal Feed                                   Health
26   Anything Capital Intensive  Social, Finance, Analytics, Advertising
27                App Discovery               News, Search and Messaging
28                App Marketing               News, Search and Messaging
29                   App Stores               News, Search and Messaging
..                          ...                                      ...
658                   Usability                                   Others
659      User Experience Design                                   Others
660              User Interface                                   Others
661                   Utilities                                   Others
662     Vending and Concessions                                   Others
663             Venture Capital  Social, Finance, Analytics, Advertising
664                  Veterinary                                   Health
665                       Video                            Entertainment
666          Video Conferencing                            Entertainment
667                 Video Games                            Entertainment
668             Video on Demand                            Entertainment
669             Video Streaming                            Entertainment
670          Virtual Workforces                            Entertainment
671                        VoIP                            Entertainment
672            Waste Management               Cleantech / Semiconductors
673                       Watch                                   Others
674                       Water               Cleantech / Semiconductors
675          Water Purification               Cleantech / Semiconductors
676                   Wearables               Cleantech / Semiconductors
677                Web Browsers               News, Search and Messaging
678                  Web Design               News, Search and Messaging
679             Web Development                                   Others
680                 Web Hosting                                   Others
681                   Web Tools                                   Others
682                    Weddings                            Entertainment
683                   Wholesale                                   Others
684            Wine And Spirits                            Entertainment
685                    Wireless                            Entertainment
686                       Women                                   Others
687                Young Adults                                   Others

[688 rows x 2 columns]

In [42]:
master_df=pd.merge(master_df, offset_mapping, how='inner', on=['primary_sector'])

In [43]:
master_df.shape

(46699, 14)

In [44]:
#Creating 3 different Data frames from 3 top english speaking coutries
d1 = master_df[master_df.country_code =='USA']
d2 = master_df[master_df.country_code =='GBR']
d3 = master_df[master_df.country_code =='IND']

In [45]:
d1.shape

(35751, 14)

In [46]:
d2.shape

(1916, 14)

In [47]:
d3.shape

(815, 14)

In [48]:
d1.head()

,permalink,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,name,category_list,status,country_code,state_code,region,city,primary_sector,Main_Sector
4,/organization/all-def-digital,/funding-round/452a2342fe720285c3b92e9bd927d9ba,venture,06-08-2014,5000000.0,All Def Digital,Media,operating,USA,CA,Los Angeles,Los Angeles,Media,Entertainment
5,/organization/audiosocket,/funding-round/0959f59e3a89bc8db8c6ed9c646349fd,venture,02-05-2013,650000.0,Audiosocket,Media|Music|Technology,operating,USA,WA,Seattle,Seattle,Media,Entertainment
6,/organization/audiosocket,/funding-round/4e3a53eec6c609943df752206070b23f,venture,02-09-2009,750000.0,Audiosocket,Media|Music|Technology,operating,USA,WA,Seattle,Seattle,Media,Entertainment
7,/organization/audiosocket,/funding-round/bc0b412cf2fa7b739e4105ad756b47a4,venture,15-02-2012,1582300.0,Audiosocket,Media|Music|Technology,operating,USA,WA,Seattle,Seattle,Media,Entertainment
8,/organization/babble,/funding-round/43cc678b39be3e684bb88501af05ff9b,venture,05-02-2009,2000000.0,Babble,Media|News|Parenting,acquired,USA,NY,New York City,New York,Media,Entertainment

In [49]:
d1.groupby("Main_Sector").count()

,permalink,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,name,category_list,status,country_code,state_code,region,city,primary_sector
Main_Sector,,,,,,,,,,,,,
Automotive & Sports,505,505,505,505,505,505,505,505,505,505,505,505,505
Cleantech / Semiconductors,7852,7852,7852,7852,7852,7852,7852,7852,7852,7852,7852,7852,7852
Entertainment,1790,1790,1790,1790,1790,1790,1790,1790,1790,1790,1790,1790,1790
Health,3262,3262,3262,3262,3262,3262,3262,3262,3262,3262,3262,3262,3262
Manufacturing,2451,2451,2451,2451,2451,2451,2451,2451,2451,2451,2451,2451,2451
"News, Search and Messaging",4341,4341,4341,4341,4341,4341,4341,4341,4341,4341,4341,4341,4341
Others,8308,8308,8308,8308,8308,8308,8308,8308,8308,8308,8308,8308,8308
"Social, Finance, Analytics, Advertising",7242,7242,7242,7242,7242,7242,7242,7242,7242,7242,7242,7242,7242

In [50]:
d2.groupby("Main_Sector").count()

,permalink,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,name,category_list,status,country_code,state_code,region,city,primary_sector
Main_Sector,,,,,,,,,,,,,
Automotive & Sports,39,39,39,39,39,39,39,39,39,39,39,39,39
Cleantech / Semiconductors,396,396,396,396,396,396,396,396,396,396,396,396,396
Entertainment,126,126,126,126,126,126,126,126,126,126,126,126,126
Health,107,107,107,107,107,107,107,107,107,107,107,107,107
Manufacturing,113,113,113,113,113,113,113,113,113,113,113,113,113
"News, Search and Messaging",230,230,230,230,230,230,230,230,230,230,230,230,230
Others,490,490,490,490,490,490,490,490,490,490,490,490,490
"Social, Finance, Analytics, Advertising",415,415,415,415,415,415,415,415,415,415,415,415,415

In [51]:
d3.groupby("Main_Sector").count()

,permalink,funding_round_permalink,funding_round_type,funded_at,raised_amount_usd,name,category_list,status,country_code,state_code,region,city,primary_sector
Main_Sector,,,,,,,,,,,,,
Automotive & Sports,30,30,30,30,30,30,30,30,30,30,30,30,30
Cleantech / Semiconductors,53,53,53,53,53,53,53,53,53,53,53,53,53
Entertainment,76,76,76,76,76,76,76,76,76,76,76,76,76
Health,42,42,42,42,42,42,42,42,42,42,42,42,42
Manufacturing,55,55,55,55,55,55,55,55,55,55,55,55,55
"News, Search and Messaging",130,130,130,130,130,130,130,130,130,130,130,130,130
Others,282,282,282,282,282,282,282,282,282,282,282,282,282
"Social, Finance, Analytics, Advertising",147,147,147,147,147,147,147,147,147,147,147,147,147